title: Emupedia
email: ""
description: ""
baseurl: ""
url: "https://emuos.emupedia.net"
markdown: kramdown
exclude:
  - .github/**
  - assets/**
  - docs/**
  - .editorconfig
  - .gitignore
  - .npmrc
  - LICENSE
  - package.json
  - package-lock.json
  - postcss.config.cjs
  - README.md
  - svelte.config.js
  - tailwind.config.cjs
  - vite.config.js
