title: EmuOS
email: ""
description: ""
baseurl: ""
url: "https://emuos.emupedia.net"
markdown: kramdown
exclude:
  - assets/**
  - 404.html
  - .gitignore
  - apple-touch-icon.png
  - favicon.ico
  - icons.html
  - indexold.html
  - manifest.webmanifest
