name: Deploy
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Purge cache emupedia.net
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_EMUPEDIA_NET }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
            - name: Purge cache emupedia.org
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_EMUPEDIA_ORG }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
            - name: Purge cache emuos.net
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_EMUOS_NET }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
            - name: Purge cache emuos.org
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_EMUOS_ORG }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}